Repository AY2324S2-CS2103T-T11-1/tp, pull requests merged in 2024-04, with the labels that each got.

#151 Deprecate Name, Phone and Address and update test cases to reflect new changes
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAttributeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersonsUuid.java
Labels: priority.high

#156 Dg update
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/PersonClassDiagram.png
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/RelationshipClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/PersonClassDiagram.png
  docs/images/RelationshipClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, help wanted, priority.high, component.UI, component.Command

#160 Fix relationship flaws
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/Relationship.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/main/java/seedu/address/model/person/relationship/RoleBasedRelationship.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipUtilTest.java
Labels: priority.medium

#168 Update user guide to match latest version v1.3
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: documentation, priority.high

#173 Tell user what to do when they enter an invalid command
  src/main/java/seedu/address/logic/Messages.java
Labels: priority.low

#174 Fix add errors
  docs/UserGuide.md
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandTest.java
Labels: type.featureFlaw

#161 Deprecate UI element classes
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.UnusedCode

#178 Update UG
  docs/UserGuide.md
Labels: documentation

#181 Fix bugs relationship
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/Relationship.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/AnySearchCommandTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersonsUuid.java
Labels: priority.medium

#185 Capitalize attribute names
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AttributeUtil.java
  src/test/java/seedu/address/logic/commands/AttributeUtilTest.java
Labels: component.Command

#171 Change clear terminal command from "clr" to "c"/"clear"
  src/main/java/seedu/address/ui/commandsection/CommandSection.java
Labels: priority.high, ignore_checks, component.UI

#194 improve add command errors
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: component.Command

#197 Improve delete behaviour
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: component.Command

#269 Update UG (PE-D feedback)
  docs/UserGuide.md
  docs/images/ClearCommandIllustration.png
Labels: documentation

#270 Fix relationship command bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommandParser.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandParserTest.java
Labels: bug

#271 test codecov
  docs/UserGuide.md
Labels: do not merge

#277 Bug with invalid relationtypes with s
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandTest.java
Labels: bug

#281 Delete feature change
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandTest.java
Labels: bug

#284 Make it so person can't be a brother and a sister etc.
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandTest.java
Labels: bug

#288 Fix bugs with loading data when editing the json file
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAttribute.java
  src/main/java/seedu/address/storage/JsonAdaptedRelationship.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersonsUuid.java
Labels: bug

#295 Fix error in gender relationships
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
Labels: bug

#299 Update Model(relationship portion) of DG.
  docs/DeveloperGuide.md
  docs/diagrams/RelationshipClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/RelationshipClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#296 Fix bug with loading data when editing json file
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: bug

#303 Attribute relationship gender
  src/main/java/seedu/address/logic/commands/AddAttributeCommand.java
  src/main/java/seedu/address/logic/commands/EditAttributeCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#306 Repackage relationship classes
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/AnySearchCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/EditRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/FamilySearchCommand.java
  src/main/java/seedu/address/logic/commands/ListRelationshipTypesCommand.java
  src/main/java/seedu/address/logic/parser/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AnySearchCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/EditRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/FamilySearchCommandParser.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedRelationship.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/AnySearchCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/EditRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/FamilySearchCommandTest.java
  src/test/java/seedu/address/logic/commands/ListRelationshipTypesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AnySearchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FamilySearchCommandParserTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipTest.java
Labels: bug

#320 DG for addRelationship Command
  docs/DeveloperGuide.md
  docs/diagrams/RelationshipAddingActivityDiagram.puml
  docs/diagrams/RoleBasedRelationshipAddingSequenceDiagram.puml
  docs/diagrams/RolelessRelationshipAddingSequenceDiagram.puml
  docs/images/RelationshipAddingActivityDiagram.png
  docs/images/RoleBasedRelationshipAddingSequenceDiagram.png
  docs/images/RolelessRelationshipAddingSequenceDiagram.png
Labels: documentation

#319 Relationship code quality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/EditRelationshipCommand.java
  src/main/java/seedu/address/logic/parser/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/EditRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/Relationship.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/main/java/seedu/address/model/person/relationship/RoleBasedRelationship.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipUtilTest.java
Labels: type.CodeQuality

#318 Improve code quality for saving features
  src/main/java/seedu/address/storage/JsonAdaptedRelationship.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.CodeQuality

#322 Add implementation text for person commands
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonActivityDiagram.puml
  docs/diagrams/AddPersonSequenceDiagram.puml
  docs/diagrams/DeletePersonActivityDiagram.puml
  docs/diagrams/DeletePersonSequenceDiagram.puml
  docs/images/AddPersonActivityDiagram.png
  docs/images/AddPersonSequenceDiagram.png
  docs/images/DeletePersonActivityDiagram.png
  docs/images/DeletePersonSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: documentation

#330 Remove extra destroy model indicator in DG
  docs/DeveloperGuide.md
  docs/diagrams/AttributeAdditionSequenceDiagram.puml
  docs/diagrams/AttributeEditSequenceDiagram.puml
  docs/diagrams/DeleteAttributeSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/AttributeAdditionSequenceDiagram.png
  docs/images/AttributeEditSequenceDiagram.png
  docs/images/DeleteAttributeSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: documentation.dg

#338 complete UG
  docs/.jekyll-metadata
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-styles.scss
Labels: documentation.ug

#342 update the UG
  docs/UserGuide.md
  docs/images/DownloadLocation.png
Labels: documentation.ug

#354 update Ug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
Labels: documentation.ug

#359 update ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation.ug
