Repository AY2324S2-CS2103T-T11-1/tp, pull requests merged in 2024-03, with the labels that each got.

#16 Add profile photo and info about ReflectiveObsidian to AboutUs
  docs/AboutUs.md
  docs/images/reflective_obsidian.png
Labels: documentation

#17 Add profile photo and info about bandov to about us
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/Bandov.jpeg
Labels: type.Story

#14 added user stories
  docs/DeveloperGuide.md
Labels: documentation

#19 Add Use Cases
  docs/DeveloperGuide.md
Labels: type.Story

#20 Add Non-Functional Requirements
  docs/DeveloperGuide.md
Labels: type.Story

#12 Update Readme and Project Page
  README.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#22 Add profile photo and info about Tsenrae to about us
  docs/AboutUs.md
  docs/images/Tsenrae.png
Labels: type.Story

#25 Update profile picture and information about Emberlynn
  docs/AboutUs.md
  docs/images/Emberlynn-Loo.png
Labels: type.Story

#29 Add attribute relationship
  src/main/java/seedu/address/model/person/Attribute.java
  src/main/java/seedu/address/model/person/BirthdayAttribute.java
  src/main/java/seedu/address/model/person/DateAttribute.java
  src/main/java/seedu/address/model/person/IntegerAttribute.java
  src/main/java/seedu/address/model/person/NameAttribute.java
  src/main/java/seedu/address/model/person/PhoneNumberAttribute.java
  src/main/java/seedu/address/model/person/SexAttribute.java
  src/main/java/seedu/address/model/person/StringAttribute.java
  src/test/java/seedu/address/model/person/AttributeTest.java
  src/test/java/seedu/address/model/person/BirthdayAttributeTest.java
  src/test/java/seedu/address/model/person/DateAttributeTest.java
  src/test/java/seedu/address/model/person/IntegerAttributeTest.java
  src/test/java/seedu/address/model/person/NameAttributeTest.java
  src/test/java/seedu/address/model/person/PhoneNumberAttributeTest.java
  src/test/java/seedu/address/model/person/SexAttributeTest.java
  src/test/java/seedu/address/model/person/StringAttributeTest.java
Labels: priority.urgent

#30 Refactor Attribute into a package
  src/main/java/seedu/address/model/person/attribute/Attribute.java
  src/main/java/seedu/address/model/person/attribute/BirthdayAttribute.java
  src/main/java/seedu/address/model/person/attribute/DateAttribute.java
  src/main/java/seedu/address/model/person/attribute/IntegerAttribute.java
  src/main/java/seedu/address/model/person/attribute/NameAttribute.java
  src/main/java/seedu/address/model/person/attribute/PhoneNumberAttribute.java
  src/main/java/seedu/address/model/person/attribute/SexAttribute.java
  src/main/java/seedu/address/model/person/attribute/StringAttribute.java
  src/test/java/seedu/address/model/person/attribute/AttributeTest.java
  src/test/java/seedu/address/model/person/attribute/BirthdayAttributeTest.java
  src/test/java/seedu/address/model/person/attribute/DateAttributeTest.java
  src/test/java/seedu/address/model/person/attribute/IntegerAttributeTest.java
  src/test/java/seedu/address/model/person/attribute/NameAttributeTest.java
  src/test/java/seedu/address/model/person/attribute/PhoneNumberAttributeTest.java
  src/test/java/seedu/address/model/person/attribute/SexAttributeTest.java
  src/test/java/seedu/address/model/person/attribute/StringAttributeTest.java
Labels: priority.high

#31 Add UUID to person
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.high

#34 Person attributes integration
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/attribute/Attribute.java
  src/main/java/seedu/address/model/person/attribute/BirthdayAttribute.java
  src/main/java/seedu/address/model/person/attribute/DateAttribute.java
  src/main/java/seedu/address/model/person/attribute/SexAttribute.java
  src/main/java/seedu/address/model/person/attribute/StringAttribute.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.urgent

#35 Add a relationship package containing relationship classes
  src/main/java/seedu/address/model/person/relationship/BioParentsRelationship.java
  src/main/java/seedu/address/model/person/relationship/FriendsRelationship.java
  src/main/java/seedu/address/model/person/relationship/Relationship.java
  src/main/java/seedu/address/model/person/relationship/RelationshipManager.java
  src/main/java/seedu/address/model/person/relationship/RoleBasedRelationship.java
  src/main/java/seedu/address/model/person/relationship/RolelessRelationship.java
  src/main/java/seedu/address/model/person/relationship/SpousesRelationship.java
  src/test/java/seedu/address/model/person/relationship/BioParentsRelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/FriendsRelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipManagerTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/RoleBasedRelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/RolelessRelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/SpousesRelationshipTest.java
Labels: priority.medium

#33 parser for attributes
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/attribute/EditPersonCommand.java
  src/main/java/seedu/address/logic/attribute/EditPersonCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/EditPersonDescriptor.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/attribute/Attribute.java
  src/main/java/seedu/address/model/person/attribute/DateAttribute.java
  src/main/java/seedu/address/model/person/attribute/IntegerAttribute.java
  src/main/java/seedu/address/model/person/attribute/StringAttribute.java
  src/test/java/seedu/address/logic/attribute/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/attribute/EditPersonCommandTest.java
  src/test/java/seedu/address/model/person/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/person/attribute/AttributeTest.java
Labels: priority.high

#36 Add parser for AddRelationshipCommand
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommandParser.java
  src/main/java/seedu/address/model/person/relationship/Relationship.java
  src/main/java/seedu/address/model/person/relationship/SpousesRelationship.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandTest.java
Labels: priority.high

#39 Add Delete Relationship parser and command files
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/model/person/relationship/RelationshipManager.java
  src/main/java/seedu/address/model/person/relationship/RoleBasedRelationship.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandTest.java
Labels: priority.high

#41 Add functionality to save Persons and their attributes
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedAttribute.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonAttr.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAttributeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonAttrTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersonsUuid.java
Labels: priority.high

#54 Add functionality to save relationships
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/relationship/Relationship.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/main/java/seedu/address/model/person/relationship/RoleBasedRelationship.java
  src/main/java/seedu/address/storage/JsonAdaptedRelationship.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java
  src/test/java/seedu/address/testutil/TypicalPersonsUuid.java
Labels: priority.high

#60 Fix relationships testcases occuring after merging
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.high

#80 Refactor attribute command location
  src/main/java/seedu/address/logic/commands/AddAttributeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAttributeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PersonAttributeCommandParser.java
  src/test/java/seedu/address/logic/attribute/AddAttributeCommandTest.java
  src/test/java/seedu/address/logic/attribute/DeleteAttributeCommandTest.java
  src/test/java/seedu/address/logic/attribute/PersonAttributeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.urgent

#85 Deprecate tokenizer, as it is superseded by more flexible attributes
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: bug, priority.medium

#87 Remove reliance on old Person Constructor in JsonAdaptedPerson
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.high

#77 Update product image
  docs/images/Ui.png
Labels: documentation

#91 Convert add and deleteAttribute commands into standalone commands with shared resources in ParserUtil
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAttributeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAttributeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PersonAttributeCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/attribute/PersonAttributeCommandParserTest.java
  src/test/java/seedu/address/logic/commands/DeleteAttributeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAttributeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandTest.java
Labels: priority.high

#90 Add functionality to delete a Person's relationships simultaneously when deleting the Person
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipUtilTest.java
Labels: priority.high

#88 Dg attribute update
  docs/DeveloperGuide.md
  docs/diagrams/AttributeClassDiagram.puml
  docs/images/AttributeClassDiagram.png
Labels: ignore_checks

#95 Update relationship
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommand.java
  src/main/java/seedu/address/logic/relationship/EditRelationshipCommandParser.java
  src/main/java/seedu/address/logic/relationship/ListRelationshipTypesCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/relationship/BioParentsRelationship.java
  src/main/java/seedu/address/model/person/relationship/FamilyRelationship.java
  src/main/java/seedu/address/model/person/relationship/FriendsRelationship.java
  src/main/java/seedu/address/model/person/relationship/Relationship.java
  src/main/java/seedu/address/model/person/relationship/RelationshipUtil.java
  src/main/java/seedu/address/model/person/relationship/RoleBasedRelationship.java
  src/main/java/seedu/address/model/person/relationship/SiblingRelationship.java
  src/main/java/seedu/address/model/person/relationship/SpousesRelationship.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/relationship/EditRelationshipCommandTest.java
  src/test/java/seedu/address/logic/relationship/ListRelationshipTypesCommandTest.java
  src/test/java/seedu/address/model/person/relationship/FamilyRelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipTest.java
  src/test/java/seedu/address/model/person/relationship/RelationshipUtilTest.java
  src/test/java/seedu/address/model/person/relationship/SiblingRelationshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersonsUuid.java
Labels: priority.high

#105 Update user guide url in help menu
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug

#102 Update dg model componet
  docs/DeveloperGuide.md
Labels: documentation

#84 Update user guide command summary
  docs/UserGuide.md
Labels: documentation, ignore_checks

#96 Enable assertions in gradle
  build.gradle
Labels: ignore_checks
